#### Simple import

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5,6])
print(arr)

### Numpy as Alias name 

In [ ]:
import numpy as np 
arr = numpy.array([0,9,8,7,6,5,4,3])
print(arr)


### Numpy Dimensions (0_D array)

In [ ]:
import numpy as np
arr = np.array(43)
print(arr)

### 2D Array

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

### 3D Array

In [ ]:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

### Check Dimensions

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5,6])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

### Array Indexing

In [ ]:
import numpy as np
arr = np.array([1,2,4,5])
print(arr[0]+ arr[3])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd Element in 1st row:',arr[0,1])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('4th element is 2nd row :',arr[1,4])


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

### Slicing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:3])

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:])

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[3:7])

### Negative slicing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:])

### Steps

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1:4])

### Data Type

In [ ]:
import numpy as np
arr = np.array(['apple','banana','orange'])
print(arr.dtype)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype='i4')
print(arr)
print(arr.dtype)

In [ ]:
import numpy as np
arr = np.array([1.1,2.2,3.3])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

In [ ]:
import numpy as np
arr = np.array([4,5,3])

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

In [ ]:
import numpy as np
arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

### Copy/View:

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

### Shapes

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4],[3,6,7,8]])
print(arr.shape)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('shape of array:',arr)

### Iterating Array(going element one by one)

In [ ]:
import numpy as np
arr = np.array([1,2,4,5])
for x in arr:
    print(x)

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
    print(x)

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr:
    for y in x:
        print(y)

In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

### Numpy Joins (Concatenate)

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

arr = np.concatenate((arr1,arr2))
print(arr)

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

arr = np.hstack((arr1,arr2))
print(arr)

### Split (Reverse of joining)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(newarr)



In [ ]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
newarr = np.hsplit(arr,3)
print(newarr)

### Searching Array

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,4,4])
x = np.where(arr == 4)
print(x)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,8])
x = np.where(arr%2==0)
print(x)


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,8])
x = np.where(arr%2==1)
print(x)

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,7])
x = np.searchsorted(arr,7)
print(x)

### Sorting Array

In [ ]:
import numpy as np
arr = np.array([9,4,2,0,5,1])
x = np.sort(arr)
print(x)

In [ ]:
import numpy as np
arr = np.array(['banana','orange','apple'])
print(np.sort(arr))

In [ ]:
import numpy as np
arr = np.array([[3,2,4],[1,0,4]])
print(np.sort(arr))

### Filter in array

In [ ]:
import numpy as np
arr = np.array([41,43,44,45])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

Create a filter array that will return only values higher than 42:

In [ ]:
import numpy as np 
arr = np.array([41,42,43,44,45,46])

filter_arr = []

for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

Create a filter array that will return only even elements from the original array:

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

filter_array = []

for element in arr:
    if element % 2 == 0:
        filter_array.append(True)
    else:
        filter_array.append(False)

newarr = arr[filter_array]

print(filter_array)
print(newarr)

## TASK's Related To Numpy

In [100]:
# Create 1D, 2D, and 3D NumPy arrays using np.array()

import numpy as np
arr1 = np.array([45])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr1)
print(arr2)
print(arr3)

[45]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [102]:
#Perform basic arithmetic operations on NumPy arrays (addition, subtraction, multiplication, division)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
sum_arr = (arr1+arr2)
sub_arr = (arr1-arr2)
mult_arr = (arr1 * arr2)
div_arr = (arr1/arr2)
print(sum_arr)
print(sub_arr)
print(mult_arr)
print(div_arr)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [110]:
#Understand how to access specific parts of an array.

arr = np.array([[1,2,3],[4,5,6]])
row = arr[1,2]
print(row)

#access entire row1
row1 = arr[1,:]
print(row1)

#access subarray
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
result = arr3[0:2,1:3]
print(result)


6
[4 5 6]
[[2 3]
 [5 6]]


In [114]:
#Filter elements in an array based on conditions (boolean indexing)
arr = np.array([1,2,3,4,5,6])
result = arr[arr>3]
print(result)


[4 5 6]


In [115]:
#Use aggregation functions like np.sum(), np.mean(), np.median(), np.std(), etc
arr = np.array([1,2,3,4,5,6])
total = np.sum(arr)
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print(total)
print(mean)
print(median)
print(std_dev)

21
3.5
3.5
1.707825127659933


In [117]:
# Learn how to stack arrays vertically (vstack) and horizontally (hstack)
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr = np.vstack((arr1,arr2))
print(arr)

arrs = np.hstack((arr1,arr2))
print(arrs)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [134]:
from numpy import random
x = random.randint(100)
print(x)

x = random.rand()
print(x)

y = random.randint(10,size=(5))
print(y)

z = random.rand(5)
print(z)

a = random.rand(1,5)
print(a)

44
0.1656880944663469
[9 7 9 8 4]
[0.48629782 0.4642626  0.91271004 0.56511627 0.56523277]
[[0.62802954 0.7722151  0.01734935 0.3553857  0.83630158]]
